name: CI - Model Training

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip' # Speeds up future runs by caching dependencies

      - name: Install MLflow and dependencies
        # Use working-directory to tell GitHub Actions to look inside the MLProject folder
        working-directory: ./MLProject
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run MLflow Project
        working-directory: ./MLProject
        run: |
          # Point mlflow directly to the local MLProject file/directory
          mlflow run . --env-manager=local \
            -P data_dir=dataset_preprocessing \
            -P n_estimators=200 \
            -P max_depth=15

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-model-artifacts
          path: |
            MLProject/mlruns/
            MLProject/artifacts/
          retention-days: 30